# Generated by Django 2.1.3 on 2018-11-16 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_scale', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_status', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name_zh', models.CharField(max_length=30)),
                ('indicator_name_en', models.CharField(max_length=60)),
                ('indicator_short_name', models.CharField(max_length=10)),
                ('unit_of_measurement', models.CharField(max_length=10)),
                ('indicator_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roe', models.CharField(max_length=20)),
                ('rota', models.CharField(max_length=20)),
                ('ros', models.CharField(max_length=20)),
                ('scsm', models.CharField(max_length=20)),
                ('rpce', models.CharField(max_length=20)),
                ('roc', models.CharField(max_length=20)),
                ('tat', models.CharField(max_length=20)),
                ('art', models.CharField(max_length=20)),
                ('bar', models.CharField(max_length=20)),
                ('cat', models.CharField(max_length=20)),
                ('cra', models.CharField(max_length=20)),
                ('alr', models.CharField(max_length=20)),
                ('ntie', models.CharField(max_length=20)),
                ('qr', models.CharField(max_length=20)),
                ('cfcr', models.CharField(max_length=20)),
                ('ibdr', models.CharField(max_length=20)),
                ('clr', models.CharField(max_length=20)),
                ('sgr', models.CharField(max_length=20)),
                ('cpar', models.CharField(max_length=20)),
                ('opgr', models.CharField(max_length=20)),
                ('tagr', models.CharField(max_length=20)),
                ('tir', models.CharField(max_length=20)),
                ('it', models.CharField(max_length=20)),
                ('tgapca', models.CharField(max_length=20)),
                ('cepoi', models.CharField(max_length=20)),
                ('evar', models.CharField(max_length=20)),
                ('ebitdar', models.CharField(max_length=20)),
                ('car', models.CharField(max_length=20)),
                ('bs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_indicator_library.BusinessScale')),
                ('bss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_indicator_library.BusinessStatus')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfEnterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_enterprise', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_indicators_zh', models.CharField(max_length=20)),
                ('type_of_indicators_en', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='indicatorsdata',
            name='te',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_indicator_library.TypeOfEnterprise'),
        ),
        migrations.AddField(
            model_name='indicators',
            name='indicator_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_indicator_library.TypeOfIndicators'),
        ),
    ]
