# Generated by Django 2.1.3 on 2018-11-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_indicator_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indicators',
            new_name='Indicator',
        ),
        migrations.RenameModel(
            old_name='IndicatorsData',
            new_name='IndicatorData',
        ),
        migrations.RenameModel(
            old_name='TypeOfIndicators',
            new_name='TypeOfIndicator',
        ),
        migrations.AlterModelOptions(
            name='businessstatus',
            options={'verbose_name_plural': 'BusinessStatus'},
        ),
        migrations.AlterModelOptions(
            name='indicatordata',
            options={'verbose_name_plural': 'IndicatorData'},
        ),
    ]
