# Generated by Django 2.1.3 on 2018-11-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_indicator_library', '0002_auto_20181116_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='indicator_description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_name_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_name_zh',
            field=models.CharField(max_length=50),
        ),
    ]
