# Generated by Django 2.1.3 on 2018-12-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_purchase_contract', models.CharField(max_length=15)),
                ('number_of_client', models.CharField(max_length=8)),
                ('product', models.CharField(max_length=20)),
                ('date_of_sale', models.DateField()),
                ('service_life', models.IntegerField()),
                ('sales_amount', models.FloatField()),
                ('tax_included_or_not', models.BooleanField()),
                ('invoiced_or_not', models.BooleanField()),
                ('number_of_invoiced', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
    ]
