# Generated by Django 2.1.3 on 2018-12-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20181220_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closed_or_not',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoiced_or_not',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_included_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
