# Generated by Django 2.1.3 on 2018-12-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20181221_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_client', models.CharField(max_length=8)),
                ('name_of_client', models.CharField(max_length=50)),
                ('taxpayer_identification_number', models.CharField(max_length=18)),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=60)),
                ('telephone', models.CharField(max_length=15)),
                ('deposit_bank', models.CharField(max_length=50)),
                ('bank_account', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='closed_or_not',
            field=models.BooleanField(choices=[(False, '未到期'), (True, '已到期')], default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoiced_or_not',
            field=models.BooleanField(choices=[(False, '未开发票'), (True, '已开发票')], default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_included_or_not',
            field=models.BooleanField(choices=[(False, '不含增值税'), (True, '含增值税')], default=False),
        ),
    ]
